#theme: jekyll-theme-slate

# SEO settings
title: "王石软件 "
title2: "技术有限公司" # default: ""
description: "产品发布"
keywords: "product, WangShi, 王石软件, C++, 罗斌城, BensonLaur"
url: http://wangshisoftware.github.io # site url
#baseurl: "//" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

#google_analytics: UA-40947781-3
#repo: http://github.com/heiswayi/thinkspace
#disqus_shortname: "bensonlaur"
#uyan_id: "2141341"
#twitter_username: "bensonlaur"
comments: true 

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "bensonlaur"
  job      : "C++ Developer"
  bio      : ""
  thumb    : /images/author.png
  email    : bensonlaur1995@gmail.com
  url      : https://bensonlaur.github.io/
  github   : https://github.com/BensonLaur
  twitter  : https://twitter.com/BensonLaur
  facebook : https://www.facebook.com/people/Benson-Laur/100009670748122
 # linkedin : http://linkedin.com/in/BensonLaur

# social settings
og_locale: "zh_CN"
twitter_card: "summary_large_image"
twitter_site: "@bensonlaur"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
